"""empty message

Revision ID: 6f75b5110f32
Revises: c228d533973f
Create Date: 2024-02-18 16:06:36.905233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f75b5110f32'
down_revision = 'c228d533973f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_db_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_db_id')
    # ### end Alembic commands ###
