"""empty message

Revision ID: c228d533973f
Revises: 6d96281450db
Create Date: 2024-02-16 18:43:00.468383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c228d533973f'
down_revision = '6d96281450db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
