"""empty message

Revision ID: d1edbfc1ae2a
Revises: ee772bdda197
Create Date: 2024-01-31 21:14:20.104741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1edbfc1ae2a'
down_revision = 'ee772bdda197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
